# Generated by Django 5.1 on 2025-04-07 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('arabic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emails', models.TextField(help_text='Comma-separated email addresses')),
                ('notify', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shared_mail_group',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(default='mohmmedshaker69@gmail.com', max_length=254)),
                ('email_host_password', models.CharField(default='qwjs resc ecdg bcxu', max_length=255)),
                ('default_from_email', models.EmailField(default='mohmmedshaker69@gmail.com', max_length=254)),
            ],
            options={
                'db_table': 'shared_mail_setting',
            },
        ),
        migrations.CreateModel(
            name='EmailGroupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('arabic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_audit_mail_group',
                'ordering': ['-change_time'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('attachment', models.FileField(upload_to='email_attachments/')),
                ('groups', models.ManyToManyField(related_name='email_messages', to='app.emailgroup')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_settings_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_audit_mail_setting',
                'ordering': ['-change_time'],
            },
        ),
    ]
