# Generated by Django 5.1 on 2025-04-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='email_photos/'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='text_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/'),
        ),
    ]
